name: hotel_booking_mlflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - pip:
    - pandas>=1.5.0
    - numpy>=1.23.0
    - scikit-learn>=1.2.0
    - mlflow>=2.8.0
    - matplotlib>=3.6.0
    - seaborn>=0.12.0
    - joblib>=1.2.0
    - click>=8.0.0
